### ISSUE TITLE
Lithuanian VAT code is not valid and is treated as a Brazilian code

### ISSUE THREAD

**Issue by DonutLaser** [se-panfilov/jsvat#113] opened 2020-12-23 06:33 UTC
```javascript
const { checkVAT, countries } = require('jsvat');

const result = checkVAT('LT100009745612', countries);
```
`result.country.name` is Brazil and isValid = false even though both of these things aren't actually true about this VAT code

**Comment by Ethan826** [comment] 2020-12-28 22:11
@se-panfilov, thanks for this helpful library! We're getting a similar problem. I apologize that I don't have the time to dig far enough into the project structure and how VATs work to offer a PR, but I think I see what the problem is, and hope this is helpful.

## Test to prove something is wrong

The problem can be reproduced by changing one of the spec files, for example [the UK one](https://github.com/se-panfilov/jsvat/blob/fd4250e8e11f628dfd290f1ca4fe11f3a0cccf34/test/unitedKingdom.spec.js#L5), thus:

```js
import { unitedKingdom, brazil } from '../index';
import { codes, invalid, name, valid, validOnlyByFormat } from './countries_vat_lists/unitedKingdom.vat';
import { addCharsToString, checkInvalidVat, checkOnlyValidFormatVat, checkValidVat } from './utils';

const countriesToTest = [brazil, unitedKingdom];

describe('United Kingdom', () => {
  it('should return "true" result for valid VATs', () => {
    valid.forEach((vat) => checkValidVat(vat, countriesToTest, codes, name));
  });

  it('should return "true" for "isSupportedCountry" and "isValidFormat" fields, but "false" for "isValid" for VATs that match format but still invalid', () => {
    validOnlyByFormat.forEach((vat) => checkOnlyValidFormatVat(vat, countriesToTest, codes, name));
  });

  it('should return "true" result for valid VATs with extra dash characters', () => {
    valid.map((vat) => addCharsToString(vat, '-')).forEach((vat) => checkValidVat(vat, countriesToTest, codes, name));
  });

  it('should return "true" result for valid VATs with extra space characters', () => {
    valid.map((vat) => addCharsToString(vat, ' ')).forEach((vat) => checkValidVat(vat, countriesToTest, codes, name));
  });

  it('should return "false" result for invalid VATs', () => {
    invalid.forEach((vat) => checkInvalidVat(vat, countriesToTest));
  });
});
```

The tests fail. But if the `countriesToTest` array is reversed, `[unitedKingdom, brazil]`, the tests pass.

## Why the test fails

The issue is in this [code](https://github.com/se-panfilov/jsvat/pull/108/files#diff-765ce34338ed82ce490a71effd8106079646bd396bfd5cb2128c3df08901d22bR31-R34). If multiple countries are selected and Brazil gets hit first while [iterating over the `countriesList`](https://github.com/se-panfilov/jsvat/blob/master/lib/es6/lib/jsvat.js#L34), the expression `!isVATStartWithCountryCode(country.name)` will always return `true` and so Brazil will always get returned. 

In other words, if Brazil is among the countries being checked for, and the correct country hasn't been hit yet, Brazil will always get returned. (That's also pretty likely to happen given that Brazil starts with _B_ and the full list is alphabetical.)

## Fixes and assumptions

One possibility is to rip out the Brazil code for now, as the library seems pretty substantially broken right now. We downgraded to 2.4.0. @DonutLaser, maybe that's the best solution for you right now?

I don't know enough about VAT numbers to know how to rewrite the Brazil special-case logic without actually running the validation code. And more to the point, the library seems to have a pretty strong assumption that there's a cheap threshold test for VAT countries before getting down to the nitty-gritty of validating the number. In other words, until Brazil got added, it was easy to look at the first few letters of the cleaned VAT and say, "If this VAT is valid for anybody, it's valid for country X."

Brazil seems to break that assumption. So it seems like there may need to be some re-thinking of how to cheaply identify the VAT country if it isn't prefixed by the country code.

And even if that is addressed for Brazil, I don't know enough about VAT numbers to know if there is more than one country _like_ Brazil. Is it possible to have a VAT code that could be valid in more than one country? How should that get handled? Because I don't know whether that's a real problem or if Brazil is truly a special case, I don't know how best to solve the issue. If I did, I'd offer a PR, and I apologize for not having the ability to dig into this enough to offer one. @andrebazoli, maybe you have some additional insights here, and please do correct me if I'm getting anything wrong.

## What test to consider adding

The test isolation is great for each country, but there should be some tests that exercise multiple countries in the `countryList` and ensure that various edge cases are covered in terms of interaction, probably by checking that behavior is correct if a country is early in the list, late in the list, etc.

**Comment by andrebazoli** [comment] 2021-01-06 06:26
Thanks, @Ethan826 for your very well detailed comment, it helped me a lot to find the issue.

**Comment by PierreF** [comment] 2021-02-03 13:37
I've also hit this bug (with French VAT, but it's really looks like the same bug). But it does not seems fixed on master (even with #114). The bug still happen when all countries are used in the country list (which is the default on https://se-panfilov.github.io/jsvat/).

I've created a tests/allCountry.spec.js that show the issue: https://github.com/PierreF/jsvat/blob/all-countries-bug/test/allCountries.spec.js

**Comment by mits87** [comment] 2021-03-20 17:09
Any progress with this bug?

**Comment by SergioGMB** [comment] 2021-04-14 11:40
https://github.com/se-panfilov/jsvat/pull/114 needs to be released to fix the bug  @mits87 @PierreF 
Nice work @andrebazoli 
Can you make a release @se-panfilov ?

**Comment by se-panfilov** [comment] 2021-04-14 11:47
Sure thing, will do it asap

**Comment by se-panfilov** [comment] 2021-04-15 20:25
Just FYI, guys (and @SergioGMB )  `2.5.1` was released =)

**Closed** 2021-04-15 20:26 UTC
